# Generated by Django 3.1.3 on 2020-11-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_auto_20201113_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(default='producto', max_length=150),
        ),
        migrations.AlterField(
            model_name='personas',
            name='nacimiento',
            field=models.DateField(blank=True),
        ),
    ]
