# Generated by Django 3.1.3 on 2020-11-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_auto_20201126_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
