# Generated by Django 3.1.3 on 2020-11-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_auto_20201126_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='cantidad',
            field=models.BigIntegerField(default=0),
        ),
    ]
